# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6a8e1a956bb0c2301764cac00a74b0bf"
name = "Synorai EcoCharge"
application_url = "https://eco-fee-automator.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
uri = "/webhooks"
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]

[access_scopes]
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://eco-fee-automator.onrender.com/auth/callback",
  "https://eco-fee-automator.onrender.com/auth/shopify/callback"
]
